---
- name: Handle New GitHub Issue
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Show GitHub Issue Info
      debug:
        msg: |
          🐛 New GitHub Issue Created!
          Title: {{ ansible_eda.event.payload.issue.title }}
          Body: {{ ansible_eda.event.payload.issue.body }}
          URL: {{ ansible_eda.event.payload.issue.html_url }}

    # Optional: do something with the issue (e.g. tag it, comment via API, etc.)
