---
- name: Respond to new GitHub issue
  hosts: localhost
  gather_facts: false
  collections:
    - community.general
  vars:
    repo_owner: "{{ ansible_eda.event.payload.repository.owner.login }}"
    repo_name: "{{ ansible_eda.event.payload.repository.name }}"
    issue_number: "{{ ansible_eda.event.payload.issue.number }}"
    issue_url: "https://api.github.com/repos/{{ repo_owner }}/{{ repo_name }}/issues/{{ issue_number }}"
    headers:
      Authorization: "Bearer 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"
      Accept: "application/vnd.github.v3+json"

  tasks:
    - name: Debug the issue info
      debug:
        msg: |
          🐛 New issue created!
          Title: {{ ansible_eda.event.payload.issue.title }}
          Body: {{ ansible_eda.event.payload.issue.body }}
          URL: {{ ansible_eda.event.payload.issue.html_url }}
    - name: Create a namespace
      kubernetes.core.k8s:
        state: present
        api_version: v1
        kind: Namespace
        name: "{{ ansible_eda.event.payload.issue.body }}"
    - name: Post a comment on the GitHub issue
      uri:
        url: "https://api.github.com/repos/{{ repo_owner }}/{{ repo_name }}/issues/{{ issue_number }}/comments"
        method: POST
        headers:
          Authorization: "token {{ token }}"
          Accept: "application/vnd.github+json"
        body: |
          {
            "body": "👋 Thanks for creating this issue! your namespace {{ ansible_eda.event.payload.issue.body }} is now created!!!."
          }
        body_format: json
        status_code: 201
    - name: close the issue 
      uri:
        url: "https://api.github.com/repos/{{ repo_owner }}/{{ repo_name }}/issues/{{ issue_number }}"
        method: PATCH
        headers:
          Authorization: "token {{ token }}"
          Accept: "application/vnd.github+json"
        body: |
          {
            "state": "closed"
          }
        body_format: json
        status_code: 201
      register: result
