- name: GitHub Webhook Rulebook
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        token: 7d52c4274cedb258e52445314e28d61e7c93bd2b
  rules:
    - name: React to GitHub Push
      condition: event.payload.ref == "refs/heads/main"
      action:
        run_job_template:
          name: github-response-template  # your AAP job template name
