- name: GitHub Webhook Rulebook
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        token: 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
  rules:
    - name: React to GitHub Push
      condition: event.payload.ref == "refs/heads/main"
      action:
        run_job_template:
          name: github-response-template  # your AAP job template name
